# Generated by Django 5.2.4 on 2025-07-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='notas.cliente'),
        ),
    ]
