# Generated by Django 5.2.4 on 2025-07-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_notafiscal_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('rg_uf_emissao', models.CharField(max_length=2, verbose_name='UF de Emissão do RG')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cnh_registro', models.CharField(max_length=20, unique=True, verbose_name='Nº de Registro da CNH')),
                ('cnh_categoria', models.CharField(max_length=5, verbose_name='Categoria da CNH')),
                ('cnh_vencimento', models.DateField(verbose_name='Vencimento da CNH')),
                ('cnh_uf_emissao', models.CharField(max_length=2, verbose_name='UF de Emissão da CNH')),
                ('cnh_codigo_seguranca', models.CharField(max_length=15, verbose_name='Código de Segurança da CNH')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('rntrc', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='RNTRC')),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('pais', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado do Veículo')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade do Veículo')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Veículo')),
                ('chassi', models.CharField(max_length=20, unique=True, verbose_name='Chassi')),
                ('renavam', models.CharField(max_length=11, unique=True, verbose_name='RENAVAM')),
                ('ano_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='notas.proprietario', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
