# Generated by Django 5.2.4 on 2025-07-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_motorista_proprietario_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_cep',
            field=models.CharField(default='00000-000', max_length=9, verbose_name='CEP do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_cidade',
            field=models.CharField(default='Nao Informada', max_length=100, verbose_name='Cidade do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_cpf_cnpj',
            field=models.CharField(default=1, max_length=18, verbose_name='CPF/CNPJ do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_endereco',
            field=models.CharField(default=1, max_length=255, verbose_name='Endereço do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_estado',
            field=models.CharField(default=1, max_length=2, verbose_name='Estado do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_nome_razao_social',
            field=models.CharField(default=1, max_length=255, verbose_name='Nome/Razão Social do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_numero',
            field=models.CharField(default=1, max_length=10, verbose_name='Número do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_telefone',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefone do Proprietário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='rntrc',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='RNTRC'),
        ),
        migrations.DeleteModel(
            name='Proprietario',
        ),
    ]
