# Generated by Django 5.2.4 on 2025-07-25 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_remove_veiculo_proprietario_veiculo_proprietario_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomaneioViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código do Romaneio')),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios', to='notas.cliente', verbose_name='Cliente')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios', to='notas.motorista', verbose_name='Motorista')),
                ('notas_fiscais', models.ManyToManyField(related_name='romaneios', to='notas.notafiscal', verbose_name='Notas Fiscais')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios', to='notas.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Romaneio de Viagem',
                'verbose_name_plural': 'Romaneios de Viagem',
                'ordering': ['-data_emissao', 'codigo'],
            },
        ),
    ]
