# Generated by Django 5.2.4 on 2025-07-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_romaneioviagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='romaneioviagem',
            options={'ordering': ['-data_emissao'], 'verbose_name_plural': 'Romaneios de Viagem'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ie',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cnh_categoria',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cnh_codigo_seguranca',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cnh_registro',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cnh_uf_emissao',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='cnh_vencimento',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='rg_uf_emissao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano_fabricacao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='chassi',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_cep',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_cidade',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_complemento',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_endereco',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_estado',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_nome_razao_social',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_numero',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario_telefone',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='renavam',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='rntrc',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Romaneada', 'Romaneada')], default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade de carga em KG', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='romaneios_cliente', to='notas.cliente'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.motorista'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='notas_fiscais',
            field=models.ManyToManyField(blank=True, related_name='romaneios', to='notas.notafiscal'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
