# Generated by Django 5.2.4 on 2025-07-30 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_cliente_bairro_cliente_complemento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='romaneioviagem',
            options={'ordering': ['-data_emissao', 'codigo'], 'verbose_name': 'Romaneio de Viagem', 'verbose_name_plural': 'Romaneios de Viagem'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa'], 'verbose_name': 'Unidade de Veículo', 'verbose_name_plural': 'Unidades de Veículos'},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='capacidade_kg',
        ),
        migrations.AddField(
            model_name='motorista',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='codigo_seguranca',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de Segurança CNH'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='numero_consulta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Consulta'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='uf_emissao_cnh',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Emissão CNH'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='vencimento_cnh',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento CNH'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='romaneios',
            field=models.ManyToManyField(blank=True, related_name='notas_vinculadas', to='notas.romaneioviagem', verbose_name='Romaneios Vinculados'),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Emitido', 'Emitido')], default='Rascunho', max_length=10, verbose_name='Status do Romaneio'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Fabricação'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Chassi'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado do Proprietário (UF)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_nome_razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome/Razão Social do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_rg_ie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG/IE do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='proprietario_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Proprietário'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Renavam'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='rntrc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RNTRC'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_unidade',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Truck', 'Caminhão Trator'), ('Reboque', 'Reboque'), ('Semi-reboque', 'Semi-reboque')], default='Truck', max_length=50, verbose_name='Tipo da Unidade de Veículo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(max_length=255, unique=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CNH'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='notas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='data',
            field=models.DateField(verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='fornecedor',
            field=models.CharField(max_length=200, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='mercadoria',
            field=models.CharField(max_length=200, verbose_name='Mercadoria'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='nota',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número da Nota'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='status',
            field=models.CharField(choices=[('Depósito', 'Depósito'), ('Enviada', 'Enviada')], default='Depósito', max_length=20, verbose_name='Status da NF'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios_cliente', to='notas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='codigo',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Código do Romaneio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_emissao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios_motorista', to='notas.motorista', verbose_name='Motorista'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='notas_fiscais',
            field=models.ManyToManyField(blank=True, related_name='romaneios_vinculados', to='notas.notafiscal', verbose_name='Notas Fiscais'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios_veiculo', to='notas.veiculo', verbose_name='Unidade de Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True, verbose_name='Placa'),
        ),
    ]
