# Generated by Django 5.2.4 on 2025-07-30 15:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0009_alter_romaneioviagem_options_alter_veiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='numero_consulta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Última Consulta'),
        ),
        migrations.CreateModel(
            name='HistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_consulta', models.CharField(max_length=50, unique=True, verbose_name='Número da Consulta')),
                ('data_consulta', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Consulta')),
                ('status_consulta', models.CharField(choices=[('Apto', 'Apto'), ('Inapto', 'Inapto'), ('Pendente', 'Pendente')], default='Pendente', max_length=20, verbose_name='Status da Consulta')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações da Consulta')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_consultas', to='notas.motorista', verbose_name='Motorista')),
            ],
            options={
                'verbose_name': 'Histórico de Consulta',
                'verbose_name_plural': 'Históricos de Consultas',
                'ordering': ['-data_consulta', 'motorista'],
            },
        ),
    ]
