# Generated by Django 5.2.4 on 2025-07-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_alter_motorista_numero_consulta_historicoconsulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='veiculo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas_associados', to='notas.veiculo', verbose_name='Veículo Principal'),
        ),
    ]
