# Generated by Django 5.2.4 on 2025-07-31 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0011_motorista_veiculo_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='reboque_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas_reboque_1', to='notas.veiculo', verbose_name='Reboque 1 (Placa 2)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='reboque_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas_reboque_2', to='notas.veiculo', verbose_name='Reboque 2 (Placa 3)'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='tipo_composicao_motorista',
            field=models.CharField(choices=[('Simples', 'Simples (Carro/Van/Truck)'), ('Carreta', 'Carreta (Caminhão Trator + 1 Reboque/Semi-reboque)'), ('Bi-trem', 'Bi-trem (Caminhão Trator + 2 Reboques/Semi-reboques)')], default='Simples', max_length=50, verbose_name='Tipo de Composição que Dirige'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='veiculo_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motoristas_veiculo_principal', to='notas.veiculo', verbose_name='Veículo Principal (Placa 1)'),
        ),
    ]
