# Generated by Django 5.2.4 on 2025-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0012_motorista_reboque_1_motorista_reboque_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Comprimento (m)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cubagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cubagem (m³)'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Largura (m)'),
        ),
    ]
