# Generated by Django 5.2.4 on 2025-07-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0013_veiculo_altura_veiculo_comprimento_veiculo_cubagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='comprimento',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cubagem',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='largura',
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='nota',
            field=models.CharField(max_length=50, verbose_name='Número da Nota'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.UniqueConstraint(fields=('nota', 'cliente', 'mercadoria', 'quantidade', 'peso'), name='unique_nota_fiscal_por_campos_chave'),
        ),
    ]
