# Generated by Django 5.2.4 on 2025-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0016_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoconsulta',
            name='gerenciadora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gerenciadora'),
        ),
    ]
