# Generated by Django 5.2.4 on 2025-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0017_historicoconsulta_gerenciadora'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
    ]
