# Generated by Django 5.2.4 on 2025-08-06 16:32

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0020_usuario_groups_usuario_is_superuser_and_more'),
    ]

    operations = [
        # Adicionar novos campos gradualmente
        migrations.AddField(
            model_name='romaneioviagem',
            name='veiculo_principal',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='romaneios_veiculo_principal',
                to='notas.veiculo',
                verbose_name='Veículo Principal'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='reboque_1',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='romaneios_reboque_1',
                to='notas.veiculo',
                verbose_name='Reboque 1'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='reboque_2',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='romaneios_reboque_2',
                to='notas.veiculo',
                verbose_name='Reboque 2'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='peso_total',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Peso Total (kg)'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='valor_total',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name='Valor Total (R$)'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='quantidade_total',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Quantidade Total'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='origem_cidade',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Cidade de Origem'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='origem_estado',
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name='Estado de Origem (UF)'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='destino_cidade',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name='Cidade de Destino'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='destino_estado',
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name='Estado de Destino (UF)'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='data_saida',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Data de Saída'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='data_chegada_prevista',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Data de Chegada Prevista'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='data_chegada_real',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Data de Chegada Real'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='seguro_obrigatorio',
            field=models.BooleanField(
                default=True,
                verbose_name='Seguro Obrigatório'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='percentual_seguro',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name='Percentual de Seguro (%)'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='valor_seguro',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Valor do Seguro (R$)'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='usuario_criacao',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='romaneios_criados',
                to='notas.usuario',
                verbose_name='Usuário de Criação'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='usuario_ultima_edicao',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='romaneios_editados',
                to='notas.usuario',
                verbose_name='Usuário da Última Edição'
            ),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='data_ultima_edicao',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Data da Última Edição'
            ),
        ),
        # Alterar o campo status para incluir novos status
        migrations.AlterField(
            model_name='romaneioviagem',
            name='status',
            field=models.CharField(
                choices=[
                    ('Rascunho', 'Rascunho'),
                    ('Emitido', 'Emitido'),
                    ('Em_Transito', 'Em Trânsito'),
                    ('Entregue', 'Entregue'),
                    ('Cancelado', 'Cancelado')
                ],
                default='Rascunho',
                max_length=15,
                verbose_name='Status do Romaneio'
            ),
        ),
        # Adicionar índices para melhor performance
        migrations.AddIndex(
            model_name='romaneioviagem',
            index=models.Index(fields=['codigo'], name='notas_roman_codigo_966bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneioviagem',
            index=models.Index(fields=['status'], name='notas_roman_status_7fe631_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneioviagem',
            index=models.Index(fields=['cliente'], name='notas_roman_cliente_6de4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneioviagem',
            index=models.Index(fields=['motorista'], name='notas_roman_motoris_ebc59f_idx'),
        ),
        migrations.AddIndex(
            model_name='romaneioviagem',
            index=models.Index(fields=['data_emissao'], name='notas_roman_data_em_ff6430_idx'),
        ),
    ]
