# Generated by Django 5.2.4 on 2025-08-06 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0021_auto_20250806_1332'),
    ]

    operations = [
        # Remover o campo veiculo antigo
        migrations.RemoveField(
            model_name='romaneioviagem',
            name='veiculo',
        ),
        # Tornar campos obrigatórios
        migrations.AlterField(
            model_name='romaneioviagem',
            name='veiculo_principal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='romaneios_veiculo_principal',
                to='notas.veiculo',
                verbose_name='Veículo Principal'
            ),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='usuario_criacao',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='romaneios_criados',
                to='notas.usuario',
                verbose_name='Usuário de Criação'
            ),
        ),
    ]
