# Generated by Django 5.2.4 on 2025-08-06 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0022_auto_20250806_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romaneioviagem',
            name='codigo',
            field=models.CharField(help_text='Código único do romaneio (ex: ROM-2024-01-0001)', max_length=20, unique=True, verbose_name='Código do Romaneio'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_chegada_prevista',
            field=models.DateTimeField(blank=True, help_text='Data e hora prevista de chegada ao destino', null=True, verbose_name='Data de Chegada Prevista'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_chegada_real',
            field=models.DateTimeField(blank=True, help_text='Data e hora real de chegada ao destino', null=True, verbose_name='Data de Chegada Real'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_saida',
            field=models.DateTimeField(blank=True, help_text='Data e hora de saída para a viagem', null=True, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='percentual_seguro',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de seguro aplicado baseado no estado de destino', max_digits=5, verbose_name='Percentual de Seguro (%)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso total da carga em quilogramas', max_digits=10, null=True, verbose_name='Peso Total (kg)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='quantidade_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quantidade total de itens', max_digits=10, null=True, verbose_name='Quantidade Total'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='reboque_1',
            field=models.ForeignKey(blank=True, help_text='Primeiro reboque (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_reboque_1', to='notas.veiculo', verbose_name='Reboque 1'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='reboque_2',
            field=models.ForeignKey(blank=True, help_text='Segundo reboque (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_reboque_2', to='notas.veiculo', verbose_name='Reboque 2'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='seguro_obrigatorio',
            field=models.BooleanField(default=True, help_text='Indica se o seguro é obrigatório para esta viagem', verbose_name='Seguro Obrigatório'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='status',
            field=models.CharField(choices=[('Salvo', 'Salvo'), ('Emitido', 'Emitido'), ('Em_Transito', 'Em Trânsito'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Salvo', max_length=15, verbose_name='Status do Romaneio'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='romaneios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='valor_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor calculado do seguro', max_digits=10, null=True, verbose_name='Valor do Seguro (R$)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da carga em reais', max_digits=12, null=True, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='veiculo_principal',
            field=models.ForeignKey(help_text='Caminhão trator, carro ou van', on_delete=django.db.models.deletion.PROTECT, related_name='romaneios_veiculo_principal', to='notas.veiculo', verbose_name='Veículo Principal'),
        ),
    ]
