# Generated by Django 5.2.4 on 2025-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0023_alter_romaneioviagem_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('pais', models.CharField(default='Brasil', max_length=50, verbose_name='País')),
                ('ativa', models.BooleanField(default=True, verbose_name='Placa Ativa')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Placa de Veículo',
                'verbose_name_plural': 'Placas de Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='motorista',
            name='tipo_composicao_motorista',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Carreta', 'Carreta (Caminhão + 1 Reboque/Semi-reboque)'), ('Bitrem', 'Bitrem (Caminhão + 2 Reboques/Semi-reboques)')], default='Caminhão', max_length=50, verbose_name='Tipo de Composição que Dirige'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_unidade',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Carreta', 'Carreta'), ('Bitrem', 'Bitrem'), ('Reboque', 'Reboque'), ('Semi-reboque', 'Semi-reboque')], default='Caminhão', max_length=50, verbose_name='Tipo da Unidade de Veículo'),
        ),
    ]
