# Generated by Django 5.2.4 on 2025-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0024_placaveiculo_tipoveiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='tipo_composicao_motorista',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Cavalo', 'Cavalo (Caminhão Trator + Reboque/Semi-reboque)'), ('Carreta', 'Carreta (Cavalo + 1 Reboque/Semi-reboque)'), ('Bitrem', 'Bitrem (Cavalo + 2 Reboques/Semi-reboques)')], default='Caminhão', max_length=50, verbose_name='Tipo de Composição que Dirige'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_unidade',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Cavalo', 'Cavalo'), ('Reboque', 'Reboque'), ('Semi-reboque', 'Semi-reboque')], default='Caminhão', max_length=50, verbose_name='Tipo da Unidade de Veículo'),
        ),
    ]
