# Generated by Django 5.2.4 on 2025-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0025_alter_motorista_tipo_composicao_motorista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='tipo_composicao_motorista',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Carreta', 'Carreta (Cavalo + 1 Reboque/Semi-reboque)'), ('Bitrem', 'Bitrem (Cavalo + 2 Reboques/Semi-reboques)')], default='Caminhão', max_length=50, verbose_name='Tipo de Composição que Dirige'),
        ),
    ]
