# Generated by Django 5.2.4 on 2025-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0026_alter_motorista_tipo_composicao_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_unidade',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Cavalo', 'Cavalo'), ('Reboque', 'Reboque'), ('Semi-reboque', 'Semi-reboque')], default='Caminhão', max_length=50, verbose_name='Tipo da Unidade de Veículo'),
        ),
    ]
