# Generated by Django 5.2.5 on 2025-09-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0028_placaveiculo_tipoveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='romaneioviagem',
            name='status',
            field=models.CharField(choices=[('Salvo', 'Salvo'), ('Emitido', 'Emitido')], default='Salvo', max_length=15, verbose_name='Status do Romaneio'),
        ),
    ]
