# Generated by Django 5.2.4 on 2025-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0029_alter_romaneioviagem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG/RNE'),
        ),
    ]
