# Generated by Django 5.2.4 on 2025-09-05 10:11

import django.db.models.deletion
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0030_motorista_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateField(help_text='Data prevista para a entrega', verbose_name='Data da Entrega')),
                ('empresa_entrega', models.CharField(help_text='Nome da empresa responsável pela entrega', max_length=255, verbose_name='Empresa que vai Entregar')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade de mercadorias a serem entregues', max_digits=10, verbose_name='Quantidade')),
                ('volume', models.CharField(help_text='Volume ou tipo de embalagem (ex: 10 caixas, 5 pallets)', max_length=100, verbose_name='Volume')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre a entrega', null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20, verbose_name='Status da Entrega')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_entregas', to='notas.cliente', verbose_name='Cliente')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agenda_entregas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Agenda de Entrega',
                'verbose_name_plural': 'Agenda de Entregas',
                'ordering': ['data_entrega', 'cliente'],
                'indexes': [models.Index(fields=['data_entrega'], name='notas_agend_data_en_59ca76_idx'), models.Index(fields=['status'], name='notas_agend_status_cfe64d_idx'), models.Index(fields=['cliente'], name='notas_agend_cliente_483a01_idx')],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
    ]
