# Generated by Django 5.2.4 on 2025-09-05 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0031_agendaentrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título resumido da tarefa', max_length=200, verbose_name='Título da Tarefa')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da tarefa', null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridade')),
                ('data_vencimento', models.DateField(blank=True, help_text='Data limite para conclusão da tarefa', null=True, verbose_name='Data de Vencimento')),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Data e hora em que a tarefa foi concluída', null=True, verbose_name='Data de Conclusão')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-prioridade', '-data_criacao'],
                'indexes': [models.Index(fields=['status'], name='notas_taref_status_eeef0a_idx'), models.Index(fields=['prioridade'], name='notas_taref_priorid_be8fce_idx'), models.Index(fields=['usuario'], name='notas_taref_usuario_651cdc_idx'), models.Index(fields=['data_vencimento'], name='notas_taref_data_ve_e1bf25_idx')],
            },
        ),
    ]
