# Generated by Django 5.2.5 on 2025-09-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0032_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
