# Generated by Django 5.2.4 on 2025-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0033_motorista_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='local',
            field=models.CharField(blank=True, choices=[('1', 'Galpão 1'), ('2', 'Galpão 2'), ('3', 'Galpão 3'), ('4', 'Galpão 4'), ('5', 'Galpão 5')], max_length=10, null=True, verbose_name='Local'),
        ),
    ]
