# Generated by Django 5.2.4 on 2025-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0034_notafiscal_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaentrega',
            name='status',
            field=models.CharField(choices=[('Agendada', 'Agendada'), ('Entregue', 'Entregue'), ('Cancelada', 'Cancelada')], default='Agendada', max_length=20, verbose_name='Status da Entrega'),
        ),
    ]
