# Generated by Django 5.2.4 on 2025-09-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0035_update_agenda_entrega_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
