# Generated by Django 5.2.4 on 2025-11-06 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0036_auto_20250912_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaCarregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(choices=[('Carregamento', 'Carregamento'), ('CTE', 'CTE'), ('Manifesto', 'Manifesto')], max_length=20, verbose_name='Tipo de Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Baixado', 'Baixado')], default='Pendente', max_length=10, verbose_name='Status')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data de Baixa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='notas.romaneioviagem', verbose_name='Romaneio')),
            ],
            options={
                'verbose_name': 'Despesa de Carregamento',
                'verbose_name_plural': 'Despesas de Carregamento',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['romaneio'], name='notas_despe_romanei_adaaa0_idx'), models.Index(fields=['status'], name='notas_despe_status_98f78b_idx'), models.Index(fields=['tipo_despesa'], name='notas_despe_tipo_de_5ddabc_idx')],
            },
        ),
    ]
