# Generated by Django 5.2.5 on 2025-11-06 11:37

from django.db import migrations, models


def converter_dados(apps, schema_editor):
    """Converte CTE e Manifesto existentes para CTE/Manifesto"""
    DespesaCarregamento = apps.get_model('notas', 'DespesaCarregamento')
    # Converter CTE e Manifesto para CTE/Manifesto
    DespesaCarregamento.objects.filter(tipo_despesa='CTE').update(tipo_despesa='CTE/Manifesto')
    DespesaCarregamento.objects.filter(tipo_despesa='Manifesto').update(tipo_despesa='CTE/Manifesto')


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0037_despesacarregamento'),
    ]

    operations = [
        migrations.RunPython(
            converter_dados,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='despesacarregamento',
            name='tipo_despesa',
            field=models.CharField(choices=[('Carregamento', 'Carregamento'), ('CTE/Manifesto', 'CTE/Manifesto')], max_length=20, verbose_name='Tipo de Despesa'),
        ),
    ]
