# Generated by Django 5.2.5 on 2025-11-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0038_unificar_cte_manifesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaCarregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_carregamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Carregamento (R$)')),
                ('valor_cte_manifesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor CTE/Manifesto (R$)')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Baixado', 'Baixado')], default='Pendente', max_length=10, verbose_name='Status')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('data_baixa', models.DateField(blank=True, null=True, verbose_name='Data de Baixa')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_carregamento', to='notas.cliente', verbose_name='Cliente')),
                ('romaneios', models.ManyToManyField(help_text='Selecione os romaneios que fazem parte desta cobrança', related_name='cobrancas_vinculadas', to='notas.romaneioviagem', verbose_name='Romaneios')),
            ],
            options={
                'verbose_name': 'Cobrança de Carregamento',
                'verbose_name_plural': 'Cobranças de Carregamento',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['cliente'], name='notas_cobra_cliente_02d9f6_idx'), models.Index(fields=['status'], name='notas_cobra_status_9dc197_idx'), models.Index(fields=['data_vencimento'], name='notas_cobra_data_ve_9d0e0c_idx')],
            },
        ),
    ]
