# Generated by Django 5.2.5 on 2025-11-13 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0039_criar_cobranca_carregamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluidos', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluidos', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluidos', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='romaneioviagem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluidos', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_excluidos', to=settings.AUTH_USER_MODEL, verbose_name='Excluído por'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='codigo',
            field=models.CharField(help_text='Código único do romaneio (ex: ROM-001, ROM-002, ROM-003...)', max_length=20, unique=True, verbose_name='Código do Romaneio'),
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão'), ('SOFT_DELETE', 'Exclusão Suave'), ('RESTORE', 'Restauração'), ('VIEW', 'Visualização'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(help_text='Nome do modelo afetado (ex: Cliente, NotaFiscal)', max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.IntegerField(blank=True, help_text='ID do registro afetado', null=True, verbose_name='ID do Objeto')),
                ('descricao', models.TextField(help_text='Descrição detalhada da ação realizada', verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, help_text='Estado do objeto antes da mudança (para updates/deletes)', null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, help_text='Estado do objeto depois da mudança (para creates/updates)', null=True, verbose_name='Dados Novos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.CharField(blank=True, help_text='Informações do navegador/cliente', max_length=500, verbose_name='User Agent')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_auditadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['usuario', 'data_hora'], name='notas_audit_usuario_08f753_idx'), models.Index(fields=['modelo', 'acao'], name='notas_audit_modelo_bf85c9_idx'), models.Index(fields=['objeto_id', 'modelo'], name='notas_audit_objeto__9d19fd_idx'), models.Index(fields=['acao', 'data_hora'], name='notas_audit_acao_2fc17d_idx')],
            },
        ),
    ]
