# Generated by Django 5.2.5 on 2025-11-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0040_cliente_deleted_at_cliente_deleted_by_and_more'),
    ]

    operations = [
        # Nota: Os campos deleted_at e deleted_by já foram removidos na migração 0041_remove_cobrancacarregamento_cliente_and_more
        # Portanto, não precisamos removê-los novamente aqui
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão'), ('SOFT_DELETE', 'Exclusão Suave'), ('RESTORE', 'Restauração'), ('VIEW', 'Visualização'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Exportação'), ('IMPORT', 'Importação'), ('IMPERSONATE', 'Impersonação'), ('END_IMPERSONATE', 'Fim de Impersonação')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='codigo',
            field=models.CharField(help_text='Código único do romaneio (ex: ROM-2024-01-0001)', max_length=20, unique=True, verbose_name='Código do Romaneio'),
        ),
        # Nota: Os modelos CobrancaCarregamento e DespesaCarregamento já foram deletados em outras migrações
    ]
