# Generated by Django 5.2.4 on 2025-11-25 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0040_cliente_deleted_at_cliente_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrancacarregamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cobrancacarregamento',
            name='romaneios',
        ),
        migrations.RemoveField(
            model_name='despesacarregamento',
            name='romaneio',
        ),
        migrations.RemoveIndex(
            model_name='auditorialog',
            name='notas_audit_usuario_08f753_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditorialog',
            name='notas_audit_modelo_bf85c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditorialog',
            name='notas_audit_objeto__9d19fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditorialog',
            name='notas_audit_acao_2fc17d_idx',
        ),
        migrations.RemoveField(
            model_name='auditorialog',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='motorista',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='romaneioviagem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='romaneioviagem',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão'), ('RESTORE', 'Restauração')], max_length=10, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='dados_anteriores',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='dados_novos',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Novos'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='objeto_id',
            field=models.IntegerField(verbose_name='ID do Objeto'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='codigo',
            field=models.CharField(help_text='Código único do romaneio (ex: ROM-2024-01-0001)', max_length=20, unique=True, verbose_name='Código do Romaneio'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['modelo', 'objeto_id'], name='notas_audit_modelo_9c191b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['-data_hora'], name='notas_audit_data_ho_c60db4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['usuario'], name='notas_audit_usuario_63610d_idx'),
        ),
        migrations.DeleteModel(
            name='CobrancaCarregamento',
        ),
        migrations.DeleteModel(
            name='DespesaCarregamento',
        ),
    ]
