# Generated by Django 5.2.4 on 2025-11-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0042_cobrancacarregamento'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['razao_social'], name='cliente_razao_social_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['status'], name='cliente_status_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['nome'], name='motorista_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['tipo_composicao_motorista'], name='motorista_tipo_composicao_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['data'], name='nota_fiscal_data_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['status'], name='nota_fiscal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['status', 'data'], name='nota_fiscal_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['cliente', 'status'], name='nota_fiscal_cliente_status_idx'),
        ),
    ]
