# Generated by Django 5.2.4 on 2025-11-28 12:57

import django.db.models.deletion
import django.utils.timezone
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0043_cliente_cliente_razao_social_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Fechamento')),
                ('frete_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Frete Total (R$)')),
                ('ctr_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CTR Total (R$)')),
                ('carregamento_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Carregamento Total (R$)')),
                ('cubagem_bau_a', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cubagem Baú A (m³)')),
                ('cubagem_bau_b', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cubagem Baú B (m³)')),
                ('cubagem_bau_c', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cubagem Baú C (m³)')),
                ('cubagem_bau_total', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automaticamente (A + B + C)', max_digits=10, null=True, verbose_name='Cubagem Baú Total (m³)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('origem_romaneio', models.BooleanField(default=False, verbose_name='Criado a partir de Romaneios')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_frete', to='notas.motorista', verbose_name='Motorista')),
                ('romaneios', models.ManyToManyField(help_text='Romaneios que compõem este fechamento', related_name='fechamentos_frete', to='notas.romaneioviagem', verbose_name='Romaneios Associados')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de Criação')),
            ],
            options={
                'verbose_name': 'Fechamento de Frete',
                'verbose_name_plural': 'Fechamentos de Frete',
                'ordering': ['-data', '-data_criacao'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ItemFechamentoFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Soma dos pesos de todos os romaneios agrupados', max_digits=10, verbose_name='Peso Total (kg)')),
                ('cubagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cubagem (m³)')),
                ('valor_mercadoria', models.DecimalField(decimal_places=2, help_text='Soma dos valores de todos os romaneios agrupados', max_digits=10, verbose_name='Valor Total (R$)')),
                ('valor_por_cubagem', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor por Cubagem (R$)')),
                ('percentual_cubagem', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentual sobre Cubagem (%)')),
                ('percentual_6', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='6,00% sobre Valor (R$)')),
                ('percentual_6_5', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='6,50% sobre Valor (R$)')),
                ('percentual_7', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='7,00% sobre Valor (R$)')),
                ('percentual_ajustado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Percentual Ajustado Manual (R$)')),
                ('frete_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete Proporcional (R$)')),
                ('ctr_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CTR Proporcional (R$)')),
                ('carregamento_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Carregamento Proporcional (R$)')),
                ('valor_final', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Final a Cobrar (R$)')),
                ('usar_ajuste_manual', models.BooleanField(default=False, verbose_name='Usar Ajuste Manual')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente_consolidado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_fechamento_consolidado', to='notas.cliente', verbose_name='Cliente Consolidado')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='notas.fechamentofrete', verbose_name='Fechamento')),
                ('romaneios', models.ManyToManyField(related_name='itens_fechamento', to='notas.romaneioviagem', verbose_name='Romaneios que Compõem')),
            ],
            options={
                'verbose_name': 'Item de Fechamento de Frete',
                'verbose_name_plural': 'Itens de Fechamento de Frete',
                'ordering': ['cliente_consolidado__razao_social'],
            },
        ),
        migrations.CreateModel(
            name='DetalheItemFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('cliente_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes_fechamento', to='notas.cliente', verbose_name='Cliente Original')),
                ('romaneio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes_fechamento', to='notas.romaneioviagem', verbose_name='Romaneio')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='notas.itemfechamentofrete', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Detalhe de Item de Fechamento',
                'verbose_name_plural': 'Detalhes de Item de Fechamento',
                'ordering': ['romaneio__codigo'],
            },
        ),
    ]
