# Generated by Django 5.2.4 on 2025-11-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0044_criar_fechamento_frete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemfechamentofrete',
            name='percentual_6',
        ),
        migrations.RemoveField(
            model_name='itemfechamentofrete',
            name='percentual_6_5',
        ),
        migrations.RemoveField(
            model_name='itemfechamentofrete',
            name='percentual_7',
        ),
        migrations.AddField(
            model_name='itemfechamentofrete',
            name='percentual_escolhido',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Percentual de 1% a 20% para cálculo', max_digits=5, verbose_name='Percentual Escolhido (%)'),
        ),
        migrations.AddField(
            model_name='itemfechamentofrete',
            name='valor_ideal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor do frete dividido pelo valor da mercadoria', max_digits=10, verbose_name='Valor Ideal (R$)'),
        ),
        migrations.AddField(
            model_name='itemfechamentofrete',
            name='valor_por_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor por Percentual (R$)'),
        ),
    ]
