# Generated by Django 5.2.4 on 2026-01-06 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0045_atualizar_campos_percentual_fechamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaNotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(help_text='Descreva a ocorrência relacionada à nota fiscal', verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, help_text='Foto relacionada à ocorrência (opcional)', null=True, upload_to='ocorrencias_notas/%Y/%m/', verbose_name='Foto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='notas.notafiscal', verbose_name='Nota Fiscal')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_notas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Registrou')),
            ],
            options={
                'verbose_name': 'Ocorrência de Nota Fiscal',
                'verbose_name_plural': 'Ocorrências de Notas Fiscais',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['nota_fiscal', 'data_criacao'], name='ocorrencia_nota_fiscal_idx')],
            },
        ),
    ]
