# Generated by Django 5.2.4 on 2026-01-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0046_ocorrencianotafiscal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencianotafiscal',
            name='foto',
        ),
        migrations.CreateModel(
            name='FotoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(help_text='Foto relacionada à ocorrência', upload_to='ocorrencias_notas/%Y/%m/', verbose_name='Foto')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='notas.ocorrencianotafiscal', verbose_name='Ocorrência')),
            ],
            options={
                'verbose_name': 'Foto de Ocorrência',
                'verbose_name_plural': 'Fotos de Ocorrências',
                'ordering': ['-data_upload'],
                'indexes': [models.Index(fields=['ocorrencia', 'data_upload'], name='foto_ocorrencia_idx')],
            },
        ),
    ]
