# Generated by Django 5.2.4 on 2026-01-06 17:25

import django.db.models.deletion
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0047_remove_ocorrencianotafiscal_foto_fotoocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_tipo', models.CharField(choices=[('Diario', 'Diário'), ('Semanal', 'Semanal')], default='Semanal', max_length=10, verbose_name='Tipo de Período')),
                ('semana_inicio', models.DateField(blank=True, null=True, verbose_name='Início da Semana')),
                ('semana_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Semana')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data (período diário)')),
                ('valor_coletado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Coletado (R$)')),
                ('valor_acertado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Acertado (R$)')),
                ('data_acerto', models.DateField(blank=True, null=True, verbose_name='Data do Acerto')),
                ('status', models.CharField(choices=[('Em_Aberto', 'Em Aberto'), ('Acertado', 'Acertado')], default='Em_Aberto', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(limit_choices_to={'tipo_usuario': 'Funcionario'}, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Caixa de Funcionário',
                'verbose_name_plural': 'Caixas de Funcionários',
                'ordering': ['-semana_inicio', '-data', 'funcionario'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ControleSaldoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Início da Semana')),
                ('semana_fim', models.DateField(verbose_name='Fim da Semana')),
                ('saldo_inicial_caixa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Inicial em Caixa (R$)')),
                ('saldo_inicial_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Inicial no Banco (R$)')),
                ('total_receitas_empresa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Receitas Empresa (R$)')),
                ('total_caixa_funcionarios', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Caixa Funcionários (R$)')),
                ('total_entradas_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Entradas Banco (R$)')),
                ('total_saidas_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Saídas Banco (R$)')),
                ('total_pendentes_receber', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Pendentes a Receber (R$)')),
                ('saldo_final_calculado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Final Calculado (R$)')),
                ('saldo_final_real_caixa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Final Real em Caixa (R$)')),
                ('saldo_final_real_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Final Real no Banco (R$)')),
                ('diferenca', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferença (R$)')),
                ('validado', models.BooleanField(default=False, help_text='Marcar quando a diferença for zero', verbose_name='Validado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_validacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Validou')),
            ],
            options={
                'verbose_name': 'Controle de Saldo Semanal',
                'verbose_name_plural': 'Controles de Saldo Semanal',
                'ordering': ['-semana_inicio'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentoCaixaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('caixa_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='notas.caixafuncionario', verbose_name='Caixa do Funcionário')),
                ('cobranca_carregamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa_funcionario', to='notas.cobrancacarregamento', verbose_name='Cobrança de Carregamento')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa do Funcionário',
                'verbose_name_plural': 'Movimentos de Caixa dos Funcionários',
                'ordering': ['-data', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReceitaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo_receita', models.CharField(choices=[('Estelar', 'Estelar'), ('CTE', 'CTE'), ('Manifesto', 'Manifesto'), ('Manutencao', 'Manutenção'), ('Outro', 'Outro')], max_length=20, verbose_name='Tipo de Receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_empresa', to='notas.cliente', verbose_name='Cliente')),
                ('cobranca_carregamento', models.ForeignKey(blank=True, help_text='Opcional: vincular a uma cobrança de carregamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_empresa', to='notas.cobrancacarregamento', verbose_name='Cobrança de Carregamento')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita da Empresa',
                'verbose_name_plural': 'Receitas da Empresa',
                'ordering': ['-data', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('Credito', 'Crédito (Entrada)'), ('Debito', 'Débito (Saída)')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('origem', models.CharField(choices=[('Manual', 'Manual'), ('Importado', 'Importado')], default='Manual', max_length=10, verbose_name='Origem')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Documento/Extrato')),
                ('hash_importacao', models.CharField(blank=True, help_text='Hash para evitar duplicatas na importação', max_length=64, null=True, verbose_name='Hash de Importação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_bancarios_criados', to=settings.AUTH_USER_MODEL)),
                ('receita_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_bancarios', to='notas.receitaempresa', verbose_name='Receita da Empresa')),
            ],
            options={
                'verbose_name': 'Movimento Bancário',
                'verbose_name_plural': 'Movimentos Bancários',
                'ordering': ['-data', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='caixafuncionario',
            index=models.Index(fields=['funcionario', 'status'], name='notas_caixa_funcion_b6e5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='caixafuncionario',
            index=models.Index(fields=['semana_inicio', 'semana_fim'], name='notas_caixa_semana__3d3906_idx'),
        ),
        migrations.AddIndex(
            model_name='caixafuncionario',
            index=models.Index(fields=['data'], name='notas_caixa_data_5089d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlesaldosemanal',
            unique_together={('semana_inicio', 'semana_fim')},
        ),
        migrations.AddIndex(
            model_name='receitaempresa',
            index=models.Index(fields=['data', 'tipo_receita'], name='notas_recei_data_68f27e_idx'),
        ),
        migrations.AddIndex(
            model_name='receitaempresa',
            index=models.Index(fields=['cobranca_carregamento'], name='notas_recei_cobranc_61aaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentobancario',
            index=models.Index(fields=['data', 'tipo'], name='notas_movim_data_c42e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentobancario',
            index=models.Index(fields=['hash_importacao'], name='notas_movim_hash_im_3c9215_idx'),
        ),
    ]
