# Generated by Django 5.2.4 on 2026-01-06 17:47

import django.db.models.deletion
import notas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0048_caixafuncionario_controlesaldosemanal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioFluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Funcionário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Funcionário (Fluxo de Caixa)',
                'verbose_name_plural': 'Funcionários (Fluxo de Caixa)',
                'ordering': ['nome'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='caixafuncionario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_funcionario', to='notas.funcionariofluxocaixa', verbose_name='Funcionário'),
        ),
    ]
