# Generated by Django 5.2.4 on 2026-01-06 18:13

import django.db.models.deletion
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0049_funcionariofluxocaixa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcertoDiarioCarregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('valor_estelar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Estelar (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acertos_diarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acerto Diário de Carregamento',
                'verbose_name_plural': 'Acertos Diários de Carregamento',
                'ordering': ['-data'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AcumuladoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Início da Semana')),
                ('semana_fim', models.DateField(verbose_name='Fim da Semana')),
                ('valor_acumulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Acumulado (R$)')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Depositado', 'Depositado')], default='Pendente', max_length=10, verbose_name='Status')),
                ('data_deposito', models.DateField(blank=True, null=True, verbose_name='Data do Depósito')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acumulados', to='notas.funcionariofluxocaixa', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Acumulado de Funcionário',
                'verbose_name_plural': 'Acumulados de Funcionários',
                'ordering': ['-semana_inicio', 'funcionario'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CarregamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('acerto_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carregamentos_cliente', to='notas.acertodiariocarregamento', verbose_name='Acerto Diário')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos_diarios', to='notas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Carregamento por Cliente',
                'verbose_name_plural': 'Carregamentos por Cliente',
                'ordering': ['cliente__razao_social'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DistribuicaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('acerto_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_funcionario', to='notas.acertodiariocarregamento', verbose_name='Acerto Diário')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes', to='notas.funcionariofluxocaixa', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Distribuição para Funcionário',
                'verbose_name_plural': 'Distribuições para Funcionários',
                'ordering': ['funcionario__nome'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='acertodiariocarregamento',
            index=models.Index(fields=['data'], name='notas_acert_data_dbc7d8_idx'),
        ),
        migrations.AddIndex(
            model_name='acumuladofuncionario',
            index=models.Index(fields=['funcionario', 'status'], name='notas_acumu_funcion_4f3c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='acumuladofuncionario',
            index=models.Index(fields=['semana_inicio', 'semana_fim'], name='notas_acumu_semana__f601d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acumuladofuncionario',
            unique_together={('funcionario', 'semana_inicio', 'semana_fim')},
        ),
        migrations.AlterUniqueTogether(
            name='carregamentocliente',
            unique_together={('acerto_diario', 'cliente')},
        ),
        migrations.AlterUniqueTogether(
            name='distribuicaofuncionario',
            unique_together={('acerto_diario', 'funcionario')},
        ),
    ]
