# Generated by Django 5.2.4 on 2026-01-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0050_acertodiariocarregamento_acumuladofuncionario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carregamentocliente',
            options={'ordering': ['cliente__razao_social', 'descricao'], 'verbose_name': 'Carregamento/Descarga', 'verbose_name_plural': 'Carregamentos e Descargas'},
        ),
        migrations.AlterUniqueTogether(
            name='carregamentocliente',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carregamentocliente',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição da descarga (quando não houver cliente)', max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='carregamentocliente',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para registrar uma descarga', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos_diarios', to='notas.cliente', verbose_name='Cliente'),
        ),
    ]
