# Generated by Django 5.2.4 on 2026-01-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0041_remove_despesacarregamento_romaneio_and_more'),
        ('notas', '0051_alter_carregamentocliente_options_and_more'),
    ]

    operations = [
    ]
