# Generated by Django 5.2.4 on 2026-01-07 14:18

import django.db.models.deletion
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0053_unificar_reboque_remover_semi_reboque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão'), ('RESTORE', 'Restauração')], max_length=10, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='tipo_composicao_motorista',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Van', 'Van'), ('Caminhão', 'Caminhão'), ('Carreta', 'Carreta (Cavalo + 1 Reboque)'), ('Bitrem', 'Bitrem (Cavalo + 2 Reboques)')], default='Caminhão', max_length=50, verbose_name='Tipo de Composição que Dirige'),
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('AcertoFuncionario', 'Acerto de Funcionário'), ('Entrada', 'Entrada de Dinheiro'), ('Saida', 'Saída de Dinheiro')], max_length=20, verbose_name='Tipo de Movimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('acerto_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='notas.acertodiariocarregamento', verbose_name='Acerto Diário')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='notas.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='notas.funcionariofluxocaixa', verbose_name='Funcionário')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Criou')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['data', 'tipo'], name='notas_movim_data_ed8ea2_idx'), models.Index(fields=['tipo', 'categoria'], name='notas_movim_tipo_f54b96_idx'), models.Index(fields=['funcionario', 'data'], name='notas_movim_funcion_cdd985_idx')],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
    ]
