# Generated by Django 5.2.4 on 2026-01-07 15:06

import django.db.models.deletion
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0054_alter_auditorialog_acao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoMovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Janeiro 2026, Semana 01/2026, etc.', max_length=100, verbose_name='Nome do Período')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Opcional. Deixe em branco se o período ainda está aberto.', null=True, verbose_name='Data de Fim')),
                ('valor_inicial_caixa', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor inicial disponível em caixa no início do período', max_digits=10, verbose_name='Valor Inicial em Caixa (R$)')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_movimento_caixa_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Criou')),
            ],
            options={
                'verbose_name': 'Período de Movimento de Caixa',
                'verbose_name_plural': 'Períodos de Movimento de Caixa',
                'ordering': ['-data_inicio', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='periodo',
            field=models.ForeignKey(blank=True, help_text='Período ao qual este movimento pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='notas.periodomovimentocaixa', verbose_name='Período'),
        ),
        migrations.AddIndex(
            model_name='periodomovimentocaixa',
            index=models.Index(fields=['status', 'data_inicio'], name='notas_perio_status_037476_idx'),
        ),
    ]
