# Generated by Django 5.2.4 on 2026-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0055_periodomovimentocaixa_movimentocaixa_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodomovimentocaixa',
            name='nome',
            field=models.CharField(blank=True, help_text='Opcional. Se não informado, será gerado automaticamente pela data de início.', max_length=100, null=True, verbose_name='Nome do Período'),
        ),
    ]
