# Generated by Django 5.2.4 on 2026-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0056_tornar_nome_periodo_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamentocliente',
            name='tipo_pagamento',
            field=models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('Deposito', 'Depósito')], default='Dinheiro', help_text='Apenas para descargas. Se for depósito, não será contabilizado no movimento de caixa.', max_length=10, null=True, verbose_name='Tipo de Pagamento'),
        ),
    ]
