# Generated by Django 5.2.4 on 2026-01-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0057_adicionar_tipo_pagamento_descarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancacarregamento',
            name='cubagem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Cubagem (m³)'),
        ),
        migrations.AddField(
            model_name='cobrancacarregamento',
            name='tipo_cliente',
            field=models.CharField(choices=[('Mensalista', 'Mensalista'), ('Por_Cubagem', 'Por Cubagem')], default='Mensalista', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='cobrancacarregamento',
            name='valor_cubagem',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor da Cubagem (R$/m³)'),
        ),
    ]
