# Generated by Django 5.2.4 on 2026-01-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0058_cobrancacarregamento_cubagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('Armazenagem', 'Armazenagem'), ('Carregamento', 'Carregamento')], max_length=20, unique=True, verbose_name='Setor')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome do Responsável/Beneficiário')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta_corrente', models.CharField(max_length=20, verbose_name='Conta Corrente')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave PIX')),
                ('tipo_chave_pix', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Email', 'Email'), ('Telefone', 'Telefone'), ('Chave Aleatória', 'Chave Aleatória')], max_length=50, verbose_name='Tipo de Chave PIX')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Dados Bancários do Setor',
                'verbose_name_plural': 'Dados Bancários dos Setores',
                'ordering': ['setor'],
            },
        ),
    ]
