# Generated by Django 5.2.5 on 2026-02-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0059_setorbancario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgendaEntrega',
        ),
    ]
