# Generated by Django 5.2.5 on 2026-02-18 13:33
# Simplificada: apenas DeleteModel na ordem correta (tabelas dependentes primeiro)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0060_remove_agenda_entrega'),
    ]

    operations = [
        migrations.DeleteModel(name='MovimentoCaixa'),
        migrations.DeleteModel(name='MovimentoCaixaFuncionario'),
        migrations.DeleteModel(name='MovimentoBancario'),
        migrations.DeleteModel(name='DistribuicaoFuncionario'),
        migrations.DeleteModel(name='CarregamentoCliente'),
        migrations.DeleteModel(name='ControleSaldoSemanal'),
        migrations.DeleteModel(name='AcumuladoFuncionario'),
        migrations.DeleteModel(name='CaixaFuncionario'),
        migrations.DeleteModel(name='ReceitaEmpresa'),
        migrations.DeleteModel(name='PeriodoMovimentoCaixa'),
        migrations.DeleteModel(name='AcertoDiarioCarregamento'),
        migrations.DeleteModel(name='FuncionarioFluxoCaixa'),
        migrations.DeleteModel(name='SetorBancario'),
    ]
