# Generated by Django 5.2.4 on 2026-02-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0061_remove_fluxo_caixa_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancacarregamento',
            name='valor_distribuicao_trabalhadores',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Valor que entra no acerto diário para divisão entre trabalhadores. Se vazio, usa o valor do carregamento.', max_digits=10, null=True, verbose_name='Valor para distribuição trabalhadores (R$)'),
        ),
        migrations.AlterField(
            model_name='cobrancacarregamento',
            name='romaneios',
            field=models.ManyToManyField(related_name='cobrancas_vinculadas', to='notas.romaneioviagem', verbose_name='Romaneios'),
        ),
        migrations.AlterField(
            model_name='fechamentofrete',
            name='cubagem_bau_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cubagem Baú Total (m³)'),
        ),
        migrations.AlterField(
            model_name='fechamentofrete',
            name='romaneios',
            field=models.ManyToManyField(related_name='fechamentos_frete', to='notas.romaneioviagem', verbose_name='Romaneios Associados'),
        ),
        migrations.AlterField(
            model_name='itemfechamentofrete',
            name='percentual_escolhido',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Percentual Escolhido (%)'),
        ),
        migrations.AlterField(
            model_name='itemfechamentofrete',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Total (kg)'),
        ),
        migrations.AlterField(
            model_name='itemfechamentofrete',
            name='valor_ideal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Ideal (R$)'),
        ),
        migrations.AlterField(
            model_name='itemfechamentofrete',
            name='valor_mercadoria',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_chegada_prevista',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Chegada Prevista'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_chegada_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Chegada Real'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='percentual_seguro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Seguro (%)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Total (kg)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='quantidade_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantidade Total'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='reboque_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_reboque_1', to='notas.veiculo', verbose_name='Reboque 1'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='reboque_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneios_reboque_2', to='notas.veiculo', verbose_name='Reboque 2'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='seguro_obrigatorio',
            field=models.BooleanField(default=True, verbose_name='Seguro Obrigatório'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='valor_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Seguro (R$)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Total (R$)'),
        ),
        migrations.AlterField(
            model_name='romaneioviagem',
            name='veiculo_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneios_veiculo_principal', to='notas.veiculo', verbose_name='Veículo Principal'),
        ),
    ]
