# Generated by Django 5.2.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0062_cobranca_valor_distribuicao_trabalhadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_maxima_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Capacidade máxima (kg)'),
        ),
    ]
