# Generated by Django 5.2.4 on 2026-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0064_clientes_ficticios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancacarregamento',
            name='valor_cte_terceiro',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Por enquanto, armazenado no modelo para cálculo futuro do lucro.', max_digits=10, null=True, verbose_name='Valor CTE/Terceiro (R$)'),
        ),
    ]
