# Generated by Django 5.2.4 on 2026-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0065_cobrancacarregamento_valor_cte_terceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancacarregamento',
            name='data_pagamento_cte_terceiro',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento CTE/Terceiro'),
        ),
        migrations.AddField(
            model_name='cobrancacarregamento',
            name='status_cte_terceiro',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=10, verbose_name='Status CTE/Terceiro'),
        ),
    ]
