# Generated by Django 5.2.5 on 2026-05-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0068_cobrancacarregamento_origem_e_descricao_avulsa'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cobrancacteavulsa',
            new_name='notas_cobra_status_9eb827_idx',
            old_name='notas_cobra_status_3ca3f6_idx',
        ),
        migrations.RenameIndex(
            model_name='cobrancacteavulsa',
            new_name='notas_cobra_status__c94e33_idx',
            old_name='notas_cobra_status__c3949f_idx',
        ),
        migrations.RenameIndex(
            model_name='cobrancacteavulsa',
            new_name='notas_cobra_criado__be73be_idx',
            old_name='notas_cobra_criado__8d6ef1_idx',
        ),
    ]
