# Generated by Django 5.2.5 on 2026-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0069_rename_notas_cobra_status_3ca3f6_idx_notas_cobra_status_9eb827_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='codigo_seguranca',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Código de Segurança CNH'),
        ),
    ]
