# Generated by Django 5.2.5 on 2026-05-07 12:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financeiro', '0003_receitaempresa_rotulo_personalizado'),
        ('notas', '0069_rename_notas_cobra_status_3ca3f6_idx_notas_cobra_status_9eb827_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('OPERACIONAL', 'Operacional'), ('ESTELAR', 'Estelar'), ('DOCUMENTACAO', 'Documentação'), ('FUNDO_GAS', 'Fundo Gás (Chapas)')], max_length=30, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('eh_terceiro', models.BooleanField(default=False, help_text='Marca dinheiro que está fisicamente no caixa mas não é da empresa.', verbose_name='É de terceiros?')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bolso',
                'verbose_name_plural': 'Bolsos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('DINHEIRO', 'Dinheiro (caixa físico)'), ('BANCO', 'Banco (conta corrente / PIX)')], max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo conhecido no dia da implantação. Lançamentos somam a partir daí.', max_digits=12, verbose_name='Saldo Inicial (R$)')),
                ('data_saldo_inicial', models.DateField(blank=True, null=True, verbose_name='Data do Saldo Inicial')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, help_text="Categoria livre, ex.: 'Xerox', 'Material', 'Acerto chapa'.", max_length=80, null=True, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('bolso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro_v2.bolso', verbose_name='Bolso')),
                ('carteira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro_v2.carteira', verbose_name='Carteira')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_v2', to='notas.cliente', verbose_name='Cliente')),
                ('cobranca_carregamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_v2', to='notas.cobrancacarregamento', verbose_name='Cobrança de Carregamento')),
                ('cobranca_cte_avulsa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_v2', to='notas.cobrancacteavulsa', verbose_name='Cobrança CTE Avulsa')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_v2_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que criou')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_v2', to='financeiro.funcionariofluxocaixa', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Lançamento (V2)',
                'verbose_name_plural': 'Lançamentos (V2)',
                'ordering': ['-data', '-criado_em'],
                'indexes': [models.Index(fields=['data'], name='financeiro__data_adf430_idx'), models.Index(fields=['carteira', 'data'], name='financeiro__carteir_c6d11d_idx'), models.Index(fields=['bolso'], name='financeiro__bolso_i_b0102c_idx'), models.Index(fields=['cliente'], name='financeiro__cliente_209108_idx'), models.Index(fields=['funcionario'], name='financeiro__funcion_7e7cc3_idx')],
            },
        ),
    ]
