# Generated by Django 5.2.4 on 2026-05-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_receitaempresa_rotulo_personalizado'),
        ('financeiro_v2', '0002_seed_carteiras_bolsos'),
        ('notas', '0069_rename_notas_cobra_status_3ca3f6_idx_notas_cobra_status_9eb827_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='acerto_diario',
            field=models.ForeignKey(blank=True, help_text='Lançamentos gerados pelo Acerto Diário V2 (idempotência).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_v2', to='financeiro.acertodiariocarregamento', verbose_name='Acerto Diário'),
        ),
        migrations.AddIndex(
            model_name='lancamento',
            index=models.Index(fields=['acerto_diario'], name='financeiro__acerto__0ba39f_idx'),
        ),
    ]
