# Generated by Django 5.2.5 on 2026-02-18 13:34

import django.db.models.deletion
import notas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0016_usuario'),  # Garante que Usuario existe antes de FKs
        ('notas', '0061_remove_fluxo_caixa_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioFluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Funcionário')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Funcionário (Fluxo de Caixa)',
                'verbose_name_plural': 'Funcionários (Fluxo de Caixa)',
                'ordering': ['nome'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SetorBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('Armazenagem', 'Armazenagem'), ('Carregamento', 'Carregamento')], max_length=20, unique=True, verbose_name='Setor')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome do Responsável/Beneficiário')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta_corrente', models.CharField(max_length=20, verbose_name='Conta Corrente')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave PIX')),
                ('tipo_chave_pix', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('Email', 'Email'), ('Telefone', 'Telefone'), ('Chave Aleatória', 'Chave Aleatória')], max_length=50, verbose_name='Tipo de Chave PIX')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Dados Bancários do Setor',
                'verbose_name_plural': 'Dados Bancários dos Setores',
                'ordering': ['setor'],
            },
        ),
        migrations.CreateModel(
            name='AcertoDiarioCarregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('valor_estelar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Estelar (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acertos_diarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acerto Diário de Carregamento',
                'verbose_name_plural': 'Acertos Diários de Carregamento',
                'ordering': ['-data'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CarregamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, help_text='Descrição da descarga (quando não houver cliente)', max_length=255, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('Dinheiro', 'Dinheiro'), ('Deposito', 'Depósito')], default='Dinheiro', help_text='Apenas para descargas. Se for depósito, não será contabilizado no movimento de caixa.', max_length=10, null=True, verbose_name='Tipo de Pagamento')),
                ('acerto_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carregamentos_cliente', to='financeiro.acertodiariocarregamento', verbose_name='Acerto Diário')),
                ('cliente', models.ForeignKey(blank=True, help_text='Deixe em branco para registrar uma descarga', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carregamentos_diarios', to='notas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Carregamento/Descarga',
                'verbose_name_plural': 'Carregamentos e Descargas',
                'ordering': ['cliente__razao_social', 'descricao'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ControleSaldoSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Início da Semana')),
                ('semana_fim', models.DateField(verbose_name='Fim da Semana')),
                ('saldo_inicial_caixa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Inicial em Caixa (R$)')),
                ('saldo_inicial_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Inicial no Banco (R$)')),
                ('total_receitas_empresa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Receitas Empresa (R$)')),
                ('total_caixa_funcionarios', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Caixa Funcionários (R$)')),
                ('total_entradas_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Entradas Banco (R$)')),
                ('total_saidas_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Saídas Banco (R$)')),
                ('total_pendentes_receber', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Pendentes a Receber (R$)')),
                ('saldo_final_calculado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Final Calculado (R$)')),
                ('saldo_final_real_caixa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Final Real em Caixa (R$)')),
                ('saldo_final_real_banco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Final Real no Banco (R$)')),
                ('diferenca', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferença (R$)')),
                ('validado', models.BooleanField(default=False, help_text='Marcar quando a diferença for zero', verbose_name='Validado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_validacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_validacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Validou')),
            ],
            options={
                'verbose_name': 'Controle de Saldo Semanal',
                'verbose_name_plural': 'Controles de Saldo Semanal',
                'ordering': ['-semana_inicio'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DistribuicaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('acerto_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuicoes_funcionario', to='financeiro.acertodiariocarregamento', verbose_name='Acerto Diário')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuicoes', to='financeiro.funcionariofluxocaixa', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Distribuição para Funcionário',
                'verbose_name_plural': 'Distribuições para Funcionários',
                'ordering': ['funcionario__nome'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CaixaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_tipo', models.CharField(choices=[('Diario', 'Diário'), ('Semanal', 'Semanal')], default='Semanal', max_length=10, verbose_name='Tipo de Período')),
                ('semana_inicio', models.DateField(blank=True, null=True, verbose_name='Início da Semana')),
                ('semana_fim', models.DateField(blank=True, null=True, verbose_name='Fim da Semana')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data (período diário)')),
                ('valor_coletado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Coletado (R$)')),
                ('valor_acertado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Acertado (R$)')),
                ('data_acerto', models.DateField(blank=True, null=True, verbose_name='Data do Acerto')),
                ('status', models.CharField(choices=[('Em_Aberto', 'Em Aberto'), ('Acertado', 'Acertado')], default='Em_Aberto', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixas_funcionario', to='financeiro.funcionariofluxocaixa', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Caixa de Funcionário',
                'verbose_name_plural': 'Caixas de Funcionários',
                'ordering': ['-semana_inicio', '-data', 'funcionario'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AcumuladoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='Início da Semana')),
                ('semana_fim', models.DateField(verbose_name='Fim da Semana')),
                ('valor_acumulado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Acumulado (R$)')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Depositado', 'Depositado')], default='Pendente', max_length=10, verbose_name='Status')),
                ('data_deposito', models.DateField(blank=True, null=True, verbose_name='Data do Depósito')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acumulados', to='financeiro.funcionariofluxocaixa', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Acumulado de Funcionário',
                'verbose_name_plural': 'Acumulados de Funcionários',
                'ordering': ['-semana_inicio', 'funcionario'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentoCaixaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('caixa_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financeiro.caixafuncionario', verbose_name='Caixa do Funcionário')),
                ('cobranca_carregamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa_funcionario', to='notas.cobrancacarregamento', verbose_name='Cobrança de Carregamento')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa do Funcionário',
                'verbose_name_plural': 'Movimentos de Caixa dos Funcionários',
                'ordering': ['-data', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PeriodoMovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Opcional. Se não informado, será gerado automaticamente pela data de início.', max_length=100, null=True, verbose_name='Nome do Período')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Opcional. Deixe em branco se o período ainda está aberto.', null=True, verbose_name='Data de Fim')),
                ('valor_inicial_caixa', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor inicial disponível em caixa no início do período', max_digits=10, verbose_name='Valor Inicial em Caixa (R$)')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=10, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_movimento_caixa_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Criou')),
            ],
            options={
                'verbose_name': 'Período de Movimento de Caixa',
                'verbose_name_plural': 'Períodos de Movimento de Caixa',
                'ordering': ['-data_inicio', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('AcertoFuncionario', 'Acerto de Funcionário'), ('Entrada', 'Entrada de Dinheiro'), ('Saida', 'Saída de Dinheiro')], max_length=20, verbose_name='Tipo de Movimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('acerto_diario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='financeiro.acertodiariocarregamento', verbose_name='Acerto Diário')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='notas.cliente', verbose_name='Cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='financeiro.funcionariofluxocaixa', verbose_name='Funcionário')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_caixa_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que Criou')),
                ('periodo', models.ForeignKey(blank=True, help_text='Período ao qual este movimento pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='financeiro.periodomovimentocaixa', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'ordering': ['-data', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ReceitaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo_receita', models.CharField(choices=[('Estelar', 'Estelar'), ('CTE', 'CTE'), ('Manifesto', 'Manifesto'), ('Manutencao', 'Manutenção'), ('Outro', 'Outro')], max_length=20, verbose_name='Tipo de Receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_empresa', to='notas.cliente', verbose_name='Cliente')),
                ('cobranca_carregamento', models.ForeignKey(blank=True, help_text='Opcional: vincular a uma cobrança de carregamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas_empresa', to='notas.cobrancacarregamento', verbose_name='Cobrança de Carregamento')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita da Empresa',
                'verbose_name_plural': 'Receitas da Empresa',
                'ordering': ['-data', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimentoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('Credito', 'Crédito (Entrada)'), ('Debito', 'Débito (Saída)')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('origem', models.CharField(choices=[('Manual', 'Manual'), ('Importado', 'Importado')], default='Manual', max_length=10, verbose_name='Origem')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Documento/Extrato')),
                ('hash_importacao', models.CharField(blank=True, help_text='Hash para evitar duplicatas na importação', max_length=64, null=True, verbose_name='Hash de Importação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_bancarios_criados', to=settings.AUTH_USER_MODEL)),
                ('receita_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_bancarios', to='financeiro.receitaempresa', verbose_name='Receita da Empresa')),
            ],
            options={
                'verbose_name': 'Movimento Bancário',
                'verbose_name_plural': 'Movimentos Bancários',
                'ordering': ['-data', '-criado_em'],
            },
            bases=(notas.models.UpperCaseMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='acertodiariocarregamento',
            index=models.Index(fields=['data'], name='financeiro__data_4483cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='controlesaldosemanal',
            unique_together={('semana_inicio', 'semana_fim')},
        ),
        migrations.AlterUniqueTogether(
            name='distribuicaofuncionario',
            unique_together={('acerto_diario', 'funcionario')},
        ),
        migrations.AddIndex(
            model_name='caixafuncionario',
            index=models.Index(fields=['funcionario', 'status'], name='financeiro__funcion_6c3e46_idx'),
        ),
        migrations.AddIndex(
            model_name='caixafuncionario',
            index=models.Index(fields=['semana_inicio', 'semana_fim'], name='financeiro__semana__380026_idx'),
        ),
        migrations.AddIndex(
            model_name='caixafuncionario',
            index=models.Index(fields=['data'], name='financeiro__data_6e38f6_idx'),
        ),
        migrations.AddIndex(
            model_name='acumuladofuncionario',
            index=models.Index(fields=['funcionario', 'status'], name='financeiro__funcion_b5e06d_idx'),
        ),
        migrations.AddIndex(
            model_name='acumuladofuncionario',
            index=models.Index(fields=['semana_inicio', 'semana_fim'], name='financeiro__semana__0c47db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acumuladofuncionario',
            unique_together={('funcionario', 'semana_inicio', 'semana_fim')},
        ),
        migrations.AddIndex(
            model_name='periodomovimentocaixa',
            index=models.Index(fields=['status', 'data_inicio'], name='financeiro__status_bac8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['data', 'tipo'], name='financeiro__data_654969_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['tipo', 'categoria'], name='financeiro__tipo_a40b1b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentocaixa',
            index=models.Index(fields=['funcionario', 'data'], name='financeiro__funcion_edc7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='receitaempresa',
            index=models.Index(fields=['data', 'tipo_receita'], name='financeiro__data_aa7a72_idx'),
        ),
        migrations.AddIndex(
            model_name='receitaempresa',
            index=models.Index(fields=['cobranca_carregamento'], name='financeiro__cobranc_5a8f71_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentobancario',
            index=models.Index(fields=['data', 'tipo'], name='financeiro__data_1c11dd_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentobancario',
            index=models.Index(fields=['hash_importacao'], name='financeiro__hash_im_1e4f80_idx'),
        ),
    ]
