# Generated by Django 5.2.4 on 2026-02-26 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('notas', '0062_cobranca_valor_distribuicao_trabalhadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregamentocliente',
            name='cobranca_carregamento',
            field=models.ForeignKey(blank=True, help_text='Vincule quando o carregamento vier de uma cobrança', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carregamentos_acerto', to='notas.cobrancacarregamento', verbose_name='Cobrança de Carregamento'),
        ),
    ]
